"""Restream servers: sizing, provisioning and allocation."""

from src.domain.servers.allocator import (
    Allocation,
    PROVISION,
    REFUSED,
    REUSED,
    SHARED,
    allocate,
    release_for,
    request_server,
)
from src.domain.servers.instance import (
    DEFAULT_TYPE,
    TYPES,
    capacity,
    cost_for_hours,
    hourly_cost,
    normalize_type,
    smallest_for,
    supported_types,
    throughput_kbps,
)
from src.domain.servers.lifecycle import (
    DRAINING,
    FAILED,
    PROVISIONING,
    READY,
    RELEASED,
    REQUESTED,
    RestreamServer,
)
from src.domain.servers.pool import ServerPool
from src.domain.servers.region import (
    REGIONS,
    continent_of,
    label_of,
    latency_millis,
    nearest,
    normalize_region,
    supported_regions,
    within,
)

__all__ = [
    "Allocation",
    "DEFAULT_TYPE",
    "DRAINING",
    "FAILED",
    "PROVISION",
    "PROVISIONING",
    "READY",
    "REFUSED",
    "REGIONS",
    "RELEASED",
    "REQUESTED",
    "REUSED",
    "RestreamServer",
    "SHARED",
    "ServerPool",
    "TYPES",
    "allocate",
    "capacity",
    "continent_of",
    "cost_for_hours",
    "hourly_cost",
    "label_of",
    "latency_millis",
    "nearest",
    "normalize_region",
    "normalize_type",
    "release_for",
    "request_server",
    "smallest_for",
    "supported_regions",
    "supported_types",
    "throughput_kbps",
    "within",
]
