"""empty message

Revision ID: 03c59b76e3e1
Revises: 11de14e08be6
Create Date: 2021-01-13 06:54:28.470264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c59b76e3e1'
down_revision = '11de14e08be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_configuration',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('CONFIG_VERSION', sa.Integer(), nullable=False),
    sa.Column('autoSwitchEnabledAfterInto', sa.Boolean(), nullable=True),
    sa.Column('autoSwitchMinLevel', sa.Integer(), nullable=False),
    sa.Column('intro_host_scene', sa.String(length=1024), nullable=True),
    sa.Column('intro_mics_fadeIn_time', sa.Integer(), nullable=False),
    sa.Column('intro_start_delay_after_streaming_start', sa.Integer(), nullable=False),
    sa.Column('obs_enable_recording', sa.Boolean(), nullable=True),
    sa.Column('obs_enable_streaming', sa.Boolean(), nullable=True),
    sa.Column('obs_host', sa.String(length=256), nullable=True),
    sa.Column('obs_password', sa.String(length=256), nullable=True),
    sa.Column('obs_port', sa.Integer(), nullable=False),
    sa.Column('obs_profilename', sa.String(length=256), nullable=False),
    sa.Column('obs_scenecollectionname', sa.String(length=256), nullable=False),
    sa.Column('recording_start_delay', sa.Integer(), nullable=False),
    sa.Column('show_start_delay', sa.Integer(), nullable=False),
    sa.Column('time_to_switch_to_intro_with_host', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_configuration')
    # ### end Alembic commands ###
