"""add uploading platforms

Revision ID: 09ff3434a646
Revises: 396a2087319d
Create Date: 2020-12-23 18:23:37.407134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ff3434a646'
down_revision = '396a2087319d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploading_platforms',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('service', sa.String(length=256), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False, default=0),
    sa.Column('service_email', sa.String(length=256), nullable=False),
    sa.Column('channel_id', sa.String(length=256), nullable=False),
    sa.Column('channel_name', sa.String(length=256), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.Column('refresh_token', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploading_platforms')
    # ### end Alembic commands ###
