"""empty message

Revision ID: 11de14e08be6
Revises: 3d4a3da62508
Create Date: 2021-01-13 05:26:59.532160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '11de14e08be6'
down_revision = '3d4a3da62508'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authorized_users', 'password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('uploading_platforms', 'image',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uploading_platforms', 'image',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    op.alter_column('authorized_users', 'password',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
