"""empty message

Revision ID: 1c645fbab34f
Revises: 03c59b76e3e1
Create Date: 2021-01-31 19:43:42.717852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c645fbab34f'
down_revision = '03c59b76e3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('category', sa.String(length=256), nullable=True),
    sa.Column('home_url', sa.String(length=1024), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('funding_source', sa.String(length=256), nullable=False),
    sa.Column('invoice_id', sa.String(length=256), nullable=True),
    sa.Column('product', sa.JSON(), nullable=True),
    sa.Column('payer', sa.JSON(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('product_id', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('billing_cycles', sa.JSON(), nullable=True),
    sa.Column('payment_preferences', sa.JSON(), nullable=True),
    sa.Column('taxes', sa.JSON(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('quantity_supported', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=False),
    sa.Column('subscriber', sa.JSON(), nullable=True),
    sa.Column('links', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('plans')
    op.drop_table('payments')
    op.drop_table('products')
    # ### end Alembic commands ###
