"""add media objects

Revision ID: 396a2087319d
Revises: 3e4326b9bf96
Create Date: 2020-12-23 18:22:43.374228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396a2087319d'
down_revision = '3e4326b9bf96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_objects',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_objects')
    # ### end Alembic commands ###
