"""demo miration

Revision ID: 3d4a3da62508
Revises: 
Create Date: 2020-12-28 15:25:44.813625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d4a3da62508'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('phone_number', sa.String(length=256), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('authorized_users',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=False),
    sa.Column('last_name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_objects',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('image', sa.String(length=1024), nullable=True),
    sa.Column('type', sa.String(length=256), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('streaming_platforms',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('service', sa.String(length=256), nullable=True),
    sa.Column('service_email', sa.String(length=256), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=True),
    sa.Column('stream_key', sa.String(length=256), nullable=True),
    sa.Column('ingestion_address', sa.String(length=256), nullable=True),
    sa.Column('channel_id', sa.String(length=256), nullable=False),
    sa.Column('channel_name', sa.String(length=256), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=4096), nullable=True),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uploading_platforms',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('service', sa.String(length=256), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('service_email', sa.String(length=256), nullable=False),
    sa.Column('channel_id', sa.String(length=256), nullable=True),
    sa.Column('channel_name', sa.String(length=256), nullable=True),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.Column('refresh_token', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploading_platforms')
    op.drop_table('streaming_platforms')
    op.drop_table('media_objects')
    op.drop_table('episodes')
    op.drop_table('authorized_users')
    op.drop_table('users')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
