"""empty message

Revision ID: 4d962d9211cd
Revises: 1c645fbab34f
Create Date: 2021-01-31 20:13:38.750597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d962d9211cd'
down_revision = '1c645fbab34f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('sandbox', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('sandbox', sa.Boolean(), nullable=False))
    op.add_column('subscriptions', sa.Column('sandbox', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'sandbox')
    op.drop_column('products', 'sandbox')
    op.drop_column('plans', 'sandbox')
    # ### end Alembic commands ###
