"""add relationship restrictions

Revision ID: 7ffb8c3bc8fd
Revises: 9033a22bfda5
Create Date: 2021-03-01 12:37:52.978777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ffb8c3bc8fd'
down_revision = '9033a22bfda5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('authorized_users_ibfk_1', 'authorized_users', type_='foreignkey')
    op.create_foreign_key(None, 'authorized_users', 'users', ['invited_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'authorized_users', type_='foreignkey')
    op.create_foreign_key('authorized_users_ibfk_1', 'authorized_users', 'users', ['invited_by'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
