"""empty message

Revision ID: 9033a22bfda5
Revises: 4d962d9211cd
Create Date: 2021-02-01 20:40:52.651832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9033a22bfda5'
down_revision = '4d962d9211cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('billing_info', sa.JSON(), nullable=True))
    op.add_column('subscriptions', sa.Column('plan_overridden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'plan_overridden')
    op.drop_column('subscriptions', 'billing_info')
    # ### end Alembic commands ###
